Serving images using cloudfront - cdn
singnet/snet-dapp pull request #325
Opened 2019-09-11 13:07 UTC by Vivek205

2019-09-11 13:47 UTC, Vivek205 commented
Don't merge

2019-09-12 04:42 UTC, chetankothari requested changes
Looks like the path generation helper methods could be cleaned up. I have added comments at specific places. We should be good to go once they are addressed.

2019-09-12 04:42 UTC, chetankothari commented on src/utility/constants/GetStarted.js
> +const mediaPath = (type, directory, file, extension) =>
Looks like this is being used only once. Can this be inlined?

2019-09-12 04:42 UTC, chetankothari commented on src/assets/thirdPartyServices/snet/text_generation/index.js
> +    avatar: avatarPath("JoeRogan", undefined, undefined, "png"),
You are always passing `undefined` for  orgId and serviceId. Can we remove both these params from `imgPath` and `avatarPath` methods. They seem redundant.

2019-09-12 08:01 UTC, Vivek205 commented on src/utility/constants/GetStarted.js
> +const mediaPath = (type, directory, file, extension) =>
It is already inline right.. couldn't get you. could you be  more specific..

2019-09-12 12:00 UTC, Vivek205 commented on src/utility/constants/GetStarted.js
> +const mediaPath = (type, directory, file, extension) =>
https://github.com/singnet/refactored-dapp/pull/325/commits/7eab77b820a105d28a7028cdef394ac6facca7e2

2019-09-12 12:00 UTC, Vivek205 commented on src/assets/thirdPartyServices/snet/text_generation/index.js
> +    avatar: avatarPath("JoeRogan", undefined, undefined, "png"),
https://github.com/singnet/refactored-dapp/pull/325/commits/2b93683b989705e5af8d3005611e573d8a4b76ff

2019-09-12 12:04 UTC, chetankothari approved these changes
LGTM

2019-09-12 12:30 UTC, merged