created an existing model section in service details page
singnet/snet-dapp pull request #837
Opened 2022-08-24 10:52 UTC by dasari-ananya

2022-08-24 11:05 UTC, rajeevbbqq commented on src/components/ServiceDetails/ExistingModel/ModelDetails/styles.js
> +		deleteModal: { backgroundColor: '##00000080' },
why do we need two ## for background color.

2022-08-24 11:05 UTC, rajeevbbqq commented on src/components/ServiceDetails/ExistingModel/index.js
> +					btnText="Ethrim Address"
Typo in button

2022-08-24 11:05 UTC, rajeevbbqq requested changes
Remove `package-lock.json` from PR

2022-08-24 11:51 UTC, Shyam-Khokhariya approved these changes, later dismissed

2022-08-25 04:19 UTC, rajeevbbqq approved these changes

2022-08-25 04:19 UTC, merged